name: Test build and lint
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build: # make sure build works properly
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: test build
        run: |
          npm install
          npm run build
      - name: eslint
        uses: icrawl/action-eslint@v1
      
