name: Test build and lint
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Test_build: # make sure build works properly
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Test building
        run: |
          npm run build
  ESlint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: ESlint
        run: |
          npx eslint --ext js,jsx,ts,tsx src